### PR TITLE
tpt help

### PR DESCRIPTION
**Pull request by tomasz-sroka**

### CODE REVIEW

**Comment by tanelpoder** [comment]
Btw I just pushed a few changes (including the regexp thing)

**Comment by cs2018ncsa** [comment]
i've always loved tpt-oracle but finding the right scripts can be hard if its outside of commonly used set. 

this if a fantastic addition. thanks!

**Comment by jgebal** [comment]
It would be great to add the same as a table to readme.md

**Comment by tanelpoder** [comment]
Yep, noted. I do have plans for generating proper web-facing documentation from the source too.

**Pull request merged**
